global_config:
  seed: 5959
  device: "cuda"
  is_mp: True
---
data_config:
  data_path: "./data/"
  dataset_name: "MNIST"
  num_shards: 200
  iid: True
---
fed_config:
  C: 0.2
  K: 100
  R: 500
  E: 5
  B: 10
  criterion: torch.nn.CrossEntropyLoss
  optimizer: torch.optim.SGD
---
optim_config:
  lr: 0.01
  momentum: 0.9
---
init_config:
  init_type: "xavier"
  init_gain: 1.0
  gpu_ids: [0,]
---
model_config:
  name: TwoNN
  in_features: 784
  num_hiddens: 200
  num_classes: 10

---
log_config:
  log_path: "./log/12"
  log_name:  "FL.log"
  tb_port: 5252
  tb_host: "0.0.0.0"
